export default {
  'message': '查询网关列表成功',
  'status': 200,
  'data': [{
    'deviceName': 'OBOXec4b',
    'isValid': -1,
    'online': 0,
    'building': '',
    'branchName': '',
    'roomNo': '',
    'adminId': 0,
    'oboxSerialId': '4bec1ea281'
  }, {
    'deviceName': 'OBOXec50',
    'isValid': -1,
    'online': 0,
    'building': '',
    'branchName': '',
    'roomNo': '',
    'adminId': 0,
    'oboxSerialId': '50ec1ea281'
  }, {
    'deviceName': 'OBOXec77',
    'isValid': -1,
    'online': 0,
    'building': '',
    'branchName': '',
    'roomNo': '',
    'adminId': 0,
    'oboxSerialId': '77ec1ea281'
  }, {
    'deviceName': 'OBOXeccd',
    'isValid': -1,
    'online': 0,
    'building': '',
    'branchName': '',
    'roomNo': '',
    'adminId': 0,
    'oboxSerialId': 'cdec1ea281'
  }]
}
